import { Facility } from '../types';

export const ANYANG_FACILITIES: Facility[] = [
  // ==========================================
  // 1. 자전거 상설 무료 정비센터 & 전문 정비소
  // ==========================================
  {
    id: 'fac-rep-center-1',
    name: '쌍개울 자전거 상설 무료정비센터',
    category: 'repair',
    categoryName: '무료 정비소',
    lat: 37.39557,
    lng: 126.93994,
    district: '동안구',
    address: '경기 안양시 동안구 비산동 1115 (비산교 하부 쌍개울)',
    roadAddress: '경기 안양시 동안구 관악대로 비산교 하부',
    description: '안양시 공식 직영 자전거 상설 무료정비센터. 공기주입, 펑크 수리, 브레이크 점검, 체인 윤활, 변속기 세팅 무료 지원.',
    openHours: '화~일 10:00 ~ 17:00 (월요일/법정공휴일 휴무)',
    facilityType: '상설 무료 정비센터',
    managementAgency: '안양시청 도로과',
    phone: '031-8045-2435',
    availableItems: ['자동 공기주입기', '펑크 패치 무상 수리', '체인 오일링', '전문 정비공구 일체', '브레이크/기어 장력 조절'],
  },
  {
    id: 'fac-rep-center-2',
    name: '안양천 삼덕교 하부 자전거 쉼터 & 셀프정비대',
    category: 'repair',
    categoryName: '셀프 정비소',
    lat: 37.4012,
    lng: 126.9205,
    district: '만안구',
    address: '경기 안양시 만안구 안양동 삼덕교 하부 둔치',
    description: '안양천 자전거도로 직결 쉼터. 고압 공기주입기, 스탠드 정비대 및 기본 공구 세트 비치.',
    openHours: '24시간 상시 개방',
    facilityType: '셀프 정비대',
    managementAgency: '만안구청 건설과',
    availableItems: ['급속 공기주입기', '육각렌치 세트', '페달 렌치', '공기압 게이지'],
  },
  {
    id: 'fac-rep-center-3',
    name: '평촌중앙공원 동편 자전거 셀프정비대',
    category: 'repair',
    categoryName: '셀프 정비소',
    lat: 37.3915,
    lng: 126.9582,
    district: '동안구',
    address: '경기 안양시 동안구 관양동 1601 (중앙공원 인라인장 옆)',
    roadAddress: '경기 안양시 동안구 관평로 149',
    description: '평촌중앙공원 내 자전거 거치대 옆 셀프 정비 툴바 및 스마트 태양광 공기주입기.',
    openHours: '24시간 상시 개방',
    facilityType: '셀프 정비대',
    managementAgency: '동안구청 공원관리과',
    availableItems: ['스마트 공기주입기', '십자/일자 드라이버', '타이어 레버'],
  },

  // ==========================================
  // 2. 자전거 공기주입기 (만안구 29개소 & 동안구 36개소 주요 반영)
  // ==========================================
  // [만안구 공기주입기]
  {
    id: 'fac-pump-m-1',
    name: '명학역 서측 육교밑 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.3842,
    lng: 126.9352,
    district: '만안구',
    address: '경기 안양시 만안구 안양동 530 (명학역 1번/서측 육교)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '명학역 서측 육교 하부 자전거 거치대 옆 공기주입기. 프레스타/던롭/슈레더 노즐 지원.',
    availableItems: ['기계식 자동 주입', '수동 펌프', '전 밸브 호환'],
  },
  {
    id: 'fac-pump-m-2',
    name: '만안구청 본관 정문 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.3857,
    lng: 126.9341,
    district: '만안구',
    address: '경기 안양시 만안구 안양로 128 (만안구청)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 행정지원과',
    phone: '031-8045-3178',
    description: '만안구청 민원실 앞 자전거 보관대 옆 고압 급속 공기주입기.',
    availableItems: ['급속 공기주입기', '공기압 측정'],
  },
  {
    id: 'fac-pump-m-3',
    name: '안양역 1번 출구 (롯데/엔터식스 앞) 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.4018,
    lng: 126.9228,
    district: '만안구',
    address: '경기 안양시 만안구 만안로 232 (안양역 1번 출구 광장)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '안양역 1번 출구 대형 자전거 주차타워 앞 위치. 전동 및 일반 자전거 겸용.',
    availableItems: ['자동 급속 주입기', '스마트 에어건'],
  },
  {
    id: 'fac-pump-m-4',
    name: '안양역 2번 출구 (동측 광장) 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.4026,
    lng: 126.9238,
    district: '만안구',
    address: '경기 안양시 만안구 안양동 88-1 (안양역 2번 출구)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '안양역 2번 출구 후면 자전거 보관소 앞 공기주입기.',
    availableItems: ['자동 공기주입기', '던롭/슈레더/프레스타'],
  },
  {
    id: 'fac-pump-m-5',
    name: '관악역 1번 출구 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.4192,
    lng: 126.9085,
    district: '만안구',
    address: '경기 안양시 만안구 석수로 1431 (관악역 1번 출구)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '관악역 1번 출구 횡단보도 앞 자전거 거치대 옆 공기주입기.',
    availableItems: ['기계식 자동 주입기', '공기압 게이지'],
  },
  {
    id: 'fac-pump-m-6',
    name: '관악역 2번 출구 (안양예술공원 방면) 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.4188,
    lng: 126.9096,
    district: '만안구',
    address: '경기 안양시 만안구 경수대로 1273번길 (관악역 2번 출구)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '안양예술공원 진입 방면 자전거 쉼터 앞 공기주입기.',
    availableItems: ['급속 공기주입기'],
  },
  {
    id: 'fac-pump-m-7',
    name: '석수2동 카네기거리 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.4115,
    lng: 126.9124,
    district: '만안구',
    address: '경기 안양시 만안구 석수2동 카네기거리 입구',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '석수2동 카네기거리 자전거 보관대 옆 설치.',
    availableItems: ['자동 공기주입기'],
  },
  {
    id: 'fac-pump-m-8',
    name: '안양예술공원 입구 관광안내센터 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.4248,
    lng: 126.9265,
    district: '만안구',
    address: '경기 안양시 만안구 예술공원로 131',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '예술공원 자전거 하이킹 진입로 입구 공기주입기.',
    availableItems: ['자동 공기주입기', '스마트 노즐'],
  },
  {
    id: 'fac-pump-m-9',
    name: '안양4동 행정복지센터 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.3968,
    lng: 126.9201,
    district: '만안구',
    address: '경기 안양시 만안구 삼덕로 57-7',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '안양4동 주민센터 앞 자전거 거치대 옆 공기주입기.',
    availableItems: ['자동 공기주입기'],
  },
  {
    id: 'fac-pump-m-10',
    name: '박달1동 행정복지센터 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.4045,
    lng: 126.9062,
    district: '만안구',
    address: '경기 안양시 만안구 양화로127번길 9',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '박달1동 주민센터 정문 앞 공기주입기.',
    availableItems: ['자동 공기주입기'],
  },
  {
    id: 'fac-pump-m-11',
    name: '삼덕도서관 앞 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.3985,
    lng: 126.9172,
    district: '만안구',
    address: '경기 안양시 만안구 병목안로 477-3',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '삼덕도서관 및 삼덕공원 수변 연결통로 앞 공기주입기.',
    availableItems: ['자동 공기주입기'],
  },

  // [동안구 공기주입기]
  {
    id: 'fac-pump-d-1',
    name: '인덕원역 8번 출구 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.4025,
    lng: 126.9772,
    district: '동안구',
    address: '경기 안양시 동안구 관악대로 529 (인덕원역 8번 출구 앞)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '동안구청 건설과',
    description: '인덕원역 8번 출구 대형 자전거 거치대 앞 스마트 태양광 공기주입기.',
    availableItems: ['자동 급속 주입기', '스마트 에어건', '전 밸브 지원'],
  },
  {
    id: 'fac-pump-d-2',
    name: '인덕원역 3번 출구 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.4012,
    lng: 126.9785,
    district: '동안구',
    address: '경기 안양시 동안구 흥안대로 529 (인덕원역 3번 출구)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '동안구청 건설과',
    description: '학의천 진입로 인근 인덕원역 3번 출구 자전거 거치대 옆 공기주입기.',
    availableItems: ['자동 공기주입기'],
  },
  {
    id: 'fac-pump-d-3',
    name: '동안구청 민원실 앞 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.3912,
    lng: 126.9501,
    district: '동안구',
    address: '경기 안양시 동안구 동안로 158 (동안구청 정문)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '동안구청 건설과',
    phone: '031-8045-4277',
    description: '동안구청 민원봉사실 앞 자전거 보관대 옆 고압 공기주입기.',
    availableItems: ['급속 공기주입기', '압력 게이지'],
  },
  {
    id: 'fac-pump-d-4',
    name: '범계역 롯데백화점 앞 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.3898,
    lng: 126.9512,
    district: '동안구',
    address: '경기 안양시 동안구 시민대로 180 (범계역 1/2번 출구 광장)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '동안구청 건설과',
    description: '범계역 메인 광장 자전거 주차 구역 앞 공기주입기.',
    availableItems: ['자동 공기주입기'],
  },
  {
    id: 'fac-pump-d-5',
    name: '범계역 6·7번 출구 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.3918,
    lng: 126.9525,
    district: '동안구',
    address: '경기 안양시 동안구 평촌대로 223번길 (범계역 6번 출구)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '동안구청 건설과',
    description: '범계역 북측 자전거 보관대 옆 설치.',
    availableItems: ['자동 공기주입기'],
  },
  {
    id: 'fac-pump-d-6',
    name: '평촌역 1·2번 출구 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.3942,
    lng: 126.9635,
    district: '동안구',
    address: '경기 안양시 동안구 시민대로 256 (평촌역 광장)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '동안구청 건설과',
    description: '평촌역 이마트 맞은편 자전거 거치대 옆 공기주입기.',
    availableItems: ['자동 공기주입기'],
  },
  {
    id: 'fac-pump-d-7',
    name: '평촌공원 운동장 입구 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.3928,
    lng: 126.9472,
    district: '동안구',
    address: '경기 안양시 동안구 부흥동 평촌공원',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '동안구청 공원관리과',
    description: '평촌공원 산책로 및 축구장 입구 자전거 거치대 옆.',
    availableItems: ['자동 공기주입기'],
  },
  {
    id: 'fac-pump-d-8',
    name: '학운공원 학의천 진입로 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.3982,
    lng: 126.9525,
    district: '동안구',
    address: '경기 안양시 동안구 달안로 학운공원 롤러스케이트장 앞',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '동안구청 공원관리과',
    description: '학의천 자전거전용도로로 내려가는 램프 입구 공기주입기.',
    availableItems: ['자동 급속 주입기', '공기압 측정'],
  },
  {
    id: 'fac-pump-d-9',
    name: '비산체육공원 롤러경기장 앞 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.4085,
    lng: 126.9452,
    district: '동안구',
    address: '경기 안양시 동안구 평촌대로 389 (안양종합운동장/체육공원)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '안양도시공사',
    description: '안양종합운동장 및 비산체육공원 주차장 옆 공기주입기.',
    availableItems: ['자동 공기주입기'],
  },
  {
    id: 'fac-pump-d-10',
    name: '비산2동 이마트 입구 공기주입기',
    category: 'repair',
    categoryName: '공기주입기',
    lat: 37.4015,
    lng: 126.9412,
    district: '동안구',
    address: '경기 안양시 동안구 관악대로 272 (비산2동)',
    facilityType: '기계식/수동식 겸용',
    airPumpType: '기계식O / 수동식O',
    openHours: '24시간 상시 개방',
    managementAgency: '동안구청 건설과',
    description: '비산2동 이마트 앞 자전거 거치대 옆 공기주입기.',
    availableItems: ['자동 공기주입기'],
  },

  // ==========================================
  // 3. 자전거 보관소 (만안구 46개소 / 동안구 146개소 대단위 반영)
  // ==========================================
  // [만안구 자전거 보관소]
  {
    id: 'fac-park-m-1',
    name: '안양역 1번 출구 자전거 보관소 (182대)',
    category: 'parking',
    categoryName: '자전거 보관소',
    lat: 37.4018,
    lng: 126.9228,
    district: '만안구',
    capacity: 182,
    address: '경기 안양시 만안구 안양동 88-1 (안양역 1번 출구 엔터식스 앞)',
    facilityType: '지붕형 대규모 거치대',
    cctv: true,
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '안양역 1번 출구 광장 대형 자전거 보관대. CCTV 상시 녹화 및 도난방지 잠금봉 설치 (182대 수용).',
    availableItems: ['182대 거치대', 'CCTV 방범녹화', '야간 조명', '공기주입기 연계'],
  },
  {
    id: 'fac-park-m-2',
    name: '안양역 2·3번 출구 자전거 보관소 (100대)',
    category: 'parking',
    categoryName: '자전거 보관소',
    lat: 37.4026,
    lng: 126.9238,
    district: '만안구',
    capacity: 100,
    address: '경기 안양시 만안구 만안로 232 (안양역 2,3번 출구)',
    facilityType: '지붕형 거치대',
    cctv: true,
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '안양역 2·3번 출구 방면 지붕형 거치대 (100대 수용).',
    availableItems: ['100대 거치대', 'CCTV 녹화', '도난방지봉'],
  },
  {
    id: 'fac-park-m-3',
    name: '명학역 1번 출구 (동측 광장) 보관소 (164대)',
    category: 'parking',
    categoryName: '자전거 보관소',
    lat: 37.3842,
    lng: 126.9358,
    district: '만안구',
    capacity: 164,
    address: '경기 안양시 만안구 안양동 530 (명학역 1번 출구 광장)',
    facilityType: '지붕형 대형 보관소',
    cctv: true,
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '명학역 광장 대규모 자전거 보관소 (164대 수용). 안양천 접근성 우수.',
    availableItems: ['164대 거치대', 'CCTV 방범', '도난방지 잠금시설'],
  },
  {
    id: 'fac-park-m-4',
    name: '관악역 2번 출구 보관소 (167대)',
    category: 'parking',
    categoryName: '자전거 보관소',
    lat: 37.4188,
    lng: 126.9096,
    district: '만안구',
    capacity: 167,
    address: '경기 안양시 만안구 석수1동 관악역 2번 출구',
    facilityType: '지붕형 대형 보관소',
    cctv: true,
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '관악역 2번 출구 광역 환승 자전거 보관대 (167대 수용).',
    availableItems: ['167대 거치대', 'CCTV 녹화', '비가림 캐노피'],
  },
  {
    id: 'fac-park-m-5',
    name: '석수역 2번 출구 (만안구청 방면) 보관소 (192대)',
    category: 'parking',
    categoryName: '자전거 보관소',
    lat: 37.4352,
    lng: 126.9025,
    district: '만안구',
    capacity: 192,
    address: '경기 안양시 만안구 석수2동 석수역 2번 출구',
    facilityType: '대형 복합 보관소',
    cctv: true,
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 건설과',
    description: '석수역 2번 출구 안양천 서울시계 인근 자전거 환승 주차장 (192대 수용).',
    availableItems: ['192대 거치대', 'CCTV 상시감시', '환승 보관대'],
  },
  {
    id: 'fac-park-m-6',
    name: '안양대학교 정문 자전거 보관소 (282대)',
    category: 'parking',
    categoryName: '자전거 보관소',
    lat: 37.3925,
    lng: 126.9158,
    district: '만안구',
    capacity: 282,
    address: '경기 안양시 만안구 삼덕로37번길 22 (안양대학교)',
    facilityType: '캠퍼스 대형 거치대',
    cctv: true,
    openHours: '24시간 상시 개방',
    managementAgency: '안양대학교 / 만안구청',
    description: '안양대학교 정문 및 학생회관 앞 대규모 자전거 거치대 (282대 수용).',
    availableItems: ['282대 거치대', '캠퍼스 방범'],
  },
  {
    id: 'fac-park-m-7',
    name: '삼덕공원 자전거 보관소 (48대)',
    category: 'parking',
    categoryName: '자전거 보관소',
    lat: 37.3995,
    lng: 126.9182,
    district: '만안구',
    capacity: 48,
    address: '경기 안양시 만안구 안양동 삼덕공원 정문',
    facilityType: '공원형 보관대',
    cctv: true,
    openHours: '24시간 상시 개방',
    managementAgency: '만안구청 공원관리과',
    description: '삼덕공원 산책로 입구 자전거 거치대 (48대 수용).',
    availableItems: ['48대 거치대', 'CCTV'],
  },

  // [동안구 자전거 보관소]
  {
    id: 'fac-park-d-1',
    name: '범계역 1번 출구·롯데백화점 보관소 (150대)',
    category: 'parking',
    categoryName: '자전거 보관소',
    lat: 37.3892,
    lng: 126.9515,
    district: '동안구',
    capacity: 150,
    address: '경기 안양시 동안구 호계동 1039 (범계역 1번 출구)',
    facilityType: '지붕형 대형 보관소',
    cctv: true,
    openHours: '24시간 상시 개방',
    managementAgency: '동안구청 건설과',
    description: '범계역 중심상가 및 롯데백화점 평촌점 앞 대형 자전거 주차구역 (150대 수용).',
    availableItems: ['150대 거치대', 'CCTV 방범', '도난방지 잠금봉'],
  },
  {
    id: 'fac-park-d-2',
    name: '평촌역 4-1번 출구 자전거 보관소 (70대)',
    category: 'parking',
    categoryName: '자전거 보관소',
    lat: 37.3948,
    lng: 126.9642,
    district: '동안구',
    capacity: 70,
    address: '경기 안양시 동안구 부림동 평촌역 4-1번 출구',
    facilityType: '지붕형 거치대',
    cctv: true,
    openHours: '24시간 상시 개방',
    managementAgency: '동안구청 건설과',
    description: '평촌역 4-1번 출구 한림대병원 방면 자전거 보관대 (70대 수용).',
    availableItems: ['70대 거치대', 'CCTV 녹화'],
  },
  {
    id: 'fac-park-d-3',
    name: '인덕원역 8번 출구 대형 보관소 (127대)',
    category: 'parking',
    categoryName: '자전거 보관소',
    lat: 37.4025,
    lng: 126.9772,
    district: '동안구',
    capacity: 127,
    address: '경기 안양시 동안구 관양동 1502 (인덕원역 8번 출구)',
    facilityType: '지붕형 대형 보관소',
    cctv: true,
    openHours: '24시간 상시 개방',
    managementAgency: '동안구청 건설과',
    description: '인덕원역 8번 출구 학의천·과천 방면 환승 거치대 (127대 수용).',
    availableItems: ['127대 거치대', 'CCTV 방범녹화', '공기주입기 인접'],
  },
  {
    id: 'fac-park-d-4',
    name: '안양종합운동장 정문 자전거 보관소 (224대)',
    category: 'parking',
    categoryName: '자전거 보관소',
    lat: 37.4042,
    lng: 126.9492,
    district: '동안구',
    capacity: 224,
    address: '경기 안양시 동안구 비산동 안양종합운동장 정문',
    facilityType: '체육시설 대규모 보관소',
    cctv: true,
    openHours: '24시간 상시 개방',
    managementAgency: '안양도시공사',
    description: '안양종합운동장 주경기장 및 빙상장 앞 대규모 거치대 (224대 수용).',
    availableItems: ['224대 거치대', 'CCTV 방범'],
  },
  {
    id: 'fac-park-d-5',
    name: '안양시청사 자전거 주차장 (107대)',
    category: 'parking',
    categoryName: '자전거 보관소',
    lat: 37.3942,
    lng: 126.9538,
    district: '동안구',
    capacity: 107,
    address: '경기 안양시 동안구 시민대로 235 (안양시청 본관 옆)',
    facilityType: '지붕형 관공서 보관소',
    cctv: true,
    openHours: '24시간 상시 개방',
    managementAgency: '안양시청 회계과',
    phone: '031-8045-2114',
    description: '안양시청 본관 및 민원실 옆 청사 자전거 주차장 (107대 수용).',
    availableItems: ['107대 거치대', 'CCTV 상시녹화', '비가림 지붕'],
  },
  {
    id: 'fac-park-d-6',
    name: '평촌중앙공원 북측 자전거 보관소 (60대)',
    category: 'parking',
    categoryName: '자전거 보관소',
    lat: 37.3932,
    lng: 126.9575,
    district: '동안구',
    capacity: 60,
    address: '경기 안양시 동안구 평촌대로 256 (중앙공원 북문)',
    facilityType: '공원형 거치대',
    cctv: true,
    openHours: '24시간 상시 개방',
    managementAgency: '동안구청 공원관리과',
    description: '평촌중앙공원 북측 광장 자전거 거치대 (60대 수용).',
    availableItems: ['60대 거치대', 'CCTV'],
  },

  // ==========================================
  // 4. 안양시 공중화장실 & 개방화장실 (공식 공공데이터 반영)
  // ==========================================
  // [수변 자전거도로 & 주요 공원 공중화장실]
  {
    id: 'fac-wc-stream-1',
    name: '안양천 쌍개울 둔치 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.3945,
    lng: 126.9565,
    district: '동안구',
    address: '경기 안양시 동안구 비산동 1115 (쌍개울 쉼터)',
    roadAddress: '경기 안양시 동안구 관악대로 비산교 하부',
    facilityType: '하천 둔치 공중화장실',
    openHours: '24시간 상시 개방',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: true,
    managementAgency: '안양시 생태하천과',
    phone: '031-8045-2187',
    description: '안양천과 학의천이 만나는 쌍개울 자전거 쉼터 내 24시간 안심화장실. 여성 안심비상벨 및 장애인 편의시설 완비.',
    availableItems: ['남/녀 화장실 분리', '장애인 전용칸', '경찰청 연동 안심비상벨', '기저귀 교환대', '냉난방 완비'],
  },
  {
    id: 'fac-wc-stream-2',
    name: '학의천 내손교·수변데크 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.3972,
    lng: 126.9745,
    district: '동안구',
    address: '경기 안양시 동안구 관양동 1307-173',
    facilityType: '하천 둔치 공중화장실',
    openHours: '24시간 상시 개방',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: false,
    managementAgency: '안양시 생태하천과',
    phone: '031-8045-2187',
    description: '학의천 자전거전용도로 수변 산책로 24시간 공중화장실. 안심비상벨 및 장애인 화장실 구비.',
    availableItems: ['24시간 개방', '안심비상벨', '장애인 화장실'],
  },
  {
    id: 'fac-wc-stream-3',
    name: '안양천 충훈교 둔치 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.4125,
    lng: 126.9042,
    district: '만안구',
    address: '경기 안양시 만안구 석수동 295-1 (충훈교 둔치)',
    facilityType: '하천 둔치 공중화장실',
    openHours: '24시간 상시 개방',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: true,
    managementAgency: '안양시 생태하천과',
    phone: '031-8045-2187',
    description: '충훈교 아래 안양천 벚꽃길 자전거도로변 24시간 안심 공중화장실.',
    availableItems: ['24시간 개방', '비상벨', '장애인 화장실', '기저귀 교환대'],
  },
  {
    id: 'fac-wc-stream-4',
    name: '안양천 안양대교 둔치 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.4072,
    lng: 126.9145,
    district: '만안구',
    address: '경기 안양시 만안구 안양동 864-4 (안양대교 하부)',
    facilityType: '하천 둔치 공중화장실',
    openHours: '24시간 상시 개방',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: false,
    managementAgency: '안양시 생태하천과',
    phone: '031-8045-2187',
    description: '안양대교 하부 자전거도로변 위치. 안심비상벨 및 장애인 화장실 설치.',
    availableItems: ['24시간 개방', '경찰 연계 비상벨', '남녀 분리'],
  },
  {
    id: 'fac-wc-park-1',
    name: '평촌중앙공원 관리동 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.3912,
    lng: 126.9568,
    district: '동안구',
    address: '경기 안양시 동안구 관평로 149 (평촌중앙공원 관리사무소)',
    roadAddress: '경기 안양시 동안구 관양동 1601',
    facilityType: '공원 공중화장실',
    openHours: '24시간 상시 개방',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: true,
    managementAgency: '동안구청 공원관리과',
    phone: '031-8045-5015',
    description: '평촌중앙공원 중앙 분수대 및 관리사무소 옆 대형 공중화장실. 장애인 전용칸, 기저귀 교환대, 비상벨 완비.',
    availableItems: ['24시간 상시 개방', '안심비상벨', '장애인 화장실 (대변기 2, 소변기 2)', '기저귀 교환대'],
  },
  {
    id: 'fac-wc-park-2',
    name: '삼덕공원 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.3992,
    lng: 126.9185,
    district: '만안구',
    address: '경기 안양시 만안구 병목안로 23 (안양동 782-19)',
    facilityType: '공원 공중화장실',
    openHours: '24시간 상시 개방',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: true,
    managementAgency: '만안구청 공원관리과',
    phone: '031-8045-5285',
    description: '삼덕공원 산책로 및 어린이놀이터 옆 안심 공중화장실.',
    availableItems: ['24시간 개방', '안심비상벨', '장애인 화장실', 'CCTV 방범'],
  },
  {
    id: 'fac-wc-park-3',
    name: '병목안시민공원 관리사무소 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.3825,
    lng: 126.9048,
    district: '만안구',
    address: '경기 안양시 만안구 병목안로 215 (안양9동 산82-2)',
    facilityType: '공원 공중화장실',
    openHours: '24시간 상시 개방',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: true,
    managementAgency: '만안구청 공원관리과',
    phone: '031-8045-5285',
    description: '병목안 자전거 라이딩 코스 종점 인근 시민공원 대형 안심화장실.',
    availableItems: ['24시간 개방', '비상벨', '장애인 편의시설', '음수대 인접'],
  },
  {
    id: 'fac-wc-park-4',
    name: '안양예술공원 벽천광장 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.4265,
    lng: 126.9312,
    district: '만안구',
    address: '경기 안양시 만안구 예술공원로 190 (안양동 250)',
    facilityType: '관광지 공중화장실',
    openHours: '24시간 상시 개방',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: false,
    managementAgency: '만안구청 환경위생과',
    phone: '031-8045-3511',
    description: '안양예술공원 벽천분수 및 야외공연장 인근 24시간 공중화장실.',
    availableItems: ['24시간 개방', '안심비상벨', '남녀 분리'],
  },
  {
    id: 'fac-wc-park-5',
    name: '학운공원 오픈스퀘어 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.3975,
    lng: 126.9535,
    district: '동안구',
    address: '경기 안양시 동안구 관양동 1589-2 (학운공원)',
    facilityType: '공원 공중화장실',
    openHours: '24시간 상시 개방',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: true,
    managementAgency: '동안구청 공원관리과',
    phone: '031-8045-5015',
    description: '학운공원 운동시설 및 학의천 진입로 인근 안심화장실.',
    availableItems: ['24시간 개방', '안심비상벨', '장애인 화장실'],
  },
  {
    id: 'fac-wc-gov-1',
    name: '안양시청사 1층 개방화장실',
    category: 'restroom',
    categoryName: '개방화장실',
    lat: 37.3942,
    lng: 126.9538,
    district: '동안구',
    address: '경기 안양시 동안구 시민대로 235 (안양시청 1층)',
    facilityType: '관공서 개방화장실',
    openHours: '00:00 ~ 24:00 (24시간 개방)',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: true,
    managementAgency: '안양시청 회계과',
    phone: '031-8045-2114',
    description: '안양시청 1층 로비 24시간 개방화장실. 대규모 장애인 화장실 및 기저귀 교환대, 비상벨 완비.',
    availableItems: ['24시간 개방', '안심비상벨', '장애인 화장실 (남4/여4)', '기저귀 교환대'],
  },
  {
    id: 'fac-wc-gov-2',
    name: '동안구청사 1층 개방화장실',
    category: 'restroom',
    categoryName: '개방화장실',
    lat: 37.3912,
    lng: 126.9501,
    district: '동안구',
    address: '경기 안양시 동안구 동안로 158 (동안구청 1층)',
    facilityType: '관공서 개방화장실',
    openHours: '06:00 ~ 24:00',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: false,
    managementAgency: '동안구청 자치행정과',
    phone: '031-8045-4277',
    description: '동안구청사 1~5층 화장실. 쾌적한 시설 및 안심비상벨 설치.',
    availableItems: ['광범위 개방', '장애인 화장실', '안심비상벨'],
  },
  {
    id: 'fac-wc-gov-3',
    name: '만안구청사 1층 개방화장실',
    category: 'restroom',
    categoryName: '개방화장실',
    lat: 37.3857,
    lng: 126.9341,
    district: '만안구',
    address: '경기 안양시 만안구 안양로 128 (만안구청 1층)',
    facilityType: '관공서 개방화장실',
    openHours: '06:00 ~ 22:00',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: true,
    managementAgency: '만안구청 자치행정과',
    phone: '031-8045-3178',
    description: '만안구청 청사 1층 개방화장실. 여성 안심비상벨 및 장애인 편의시설 완비.',
    availableItems: ['개방화장실', '안심비상벨', '장애인 화장실', '기저귀 교환대'],
  },
  {
    id: 'fac-wc-st-1',
    name: '안양역사 1층 및 대합실 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.4018,
    lng: 126.9228,
    district: '만안구',
    address: '경기 안양시 만안구 만안로 232 (안양역사)',
    facilityType: '철도역사 공중화장실',
    openHours: '00:00 ~ 24:00',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: true,
    managementAgency: '한국철도공사 안양역',
    phone: '031-443-9689',
    description: '안양역 1층 광장 및 2층 대합실 24시간 공중화장실. 안심비상벨 및 장애인 화장실 완비.',
    availableItems: ['24시간 개방', '안심비상벨', '장애인 화장실', '기저귀 교환대'],
  },
  {
    id: 'fac-wc-st-2',
    name: '범계역 4호선 대합실 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.3898,
    lng: 126.9508,
    district: '동안구',
    address: '경기 안양시 동안구 동안로 130 (범계역 지하 대합실)',
    facilityType: '지하철 공중화장실',
    openHours: '05:00 ~ 24:30',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: false,
    managementAgency: '코레일 범계역',
    phone: '031-384-7788',
    description: '범계역 지하 대합실 내 개방 공중화장실.',
    availableItems: ['대합실 화장실', '장애인 화장실', '비상벨'],
  },
  {
    id: 'fac-wc-st-3',
    name: '인덕원역 4호선 대합실 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.4018,
    lng: 126.9768,
    district: '동안구',
    address: '경기 안양시 동안구 관악대로 529 (인덕원역 대합실)',
    facilityType: '지하철 공중화장실',
    openHours: '05:00 ~ 24:30',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: true,
    managementAgency: '코레일 인덕원역',
    phone: '031-422-7788',
    description: '인덕원역 개찰구 인근 화장실. 안심비상벨 및 장애인 전용칸 구비.',
    availableItems: ['대합실 화장실', '안심비상벨', '장애인 화장실', '기저귀 교환대'],
  },
  {
    id: 'fac-wc-st-4',
    name: '명학역 1호선 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.3842,
    lng: 126.9352,
    district: '만안구',
    address: '경기 안양시 만안구 안양로 20 (명학역사)',
    facilityType: '철도역사 공중화장실',
    openHours: '04:30 ~ 24:20',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: true,
    managementAgency: '코레일 명학역',
    phone: '031-447-7788',
    description: '명학역 1번/2번 출구 대합실 공중화장실. 안심비상벨 설치.',
    availableItems: ['역사 화장실', '비상벨', '장애인 화장실'],
  },
  {
    id: 'fac-wc-st-5',
    name: '관악역 1호선 공중화장실',
    category: 'restroom',
    categoryName: '공중화장실',
    lat: 37.4192,
    lng: 126.9085,
    district: '만안구',
    address: '경기 안양시 만안구 석수로 1431 (관악역사)',
    facilityType: '철도역사 공중화장실',
    openHours: '04:30 ~ 24:30',
    emergencyBell: true,
    disabledToilet: true,
    cctv: true,
    diaperTable: false,
    managementAgency: '코레일 관악역',
    phone: '031-472-7788',
    description: '관악역 1호선 역사 내 개방 화장실.',
    availableItems: ['역사 화장실', '비상벨', '장애인 화장실'],
  },

  // ==========================================
  // 5. 음수대 (수변 자전거도로 & 주요 공원)
  // ==========================================
  {
    id: 'fac-wat-1',
    name: '쌍개울 수변 쉼터 음수대',
    category: 'water',
    categoryName: '음수대',
    lat: 37.3946,
    lng: 126.9567,
    district: '동안구',
    address: '경기 안양시 동안구 비산교 하부 쌍개울 광장',
    description: '안양천-학의천 합류부 라이더 전용 아리수급 수질검사 완료 음수대.',
    openHours: '상시 이용 가능 (동절기 제외)',
    facilityType: '수변 음수대',
    managementAgency: '안양시 수도시설과',
    availableItems: ['정수 수질검사 필증', '자전거 물통 직수 레버', '반려견 음수 트레이'],
  },
  {
    id: 'fac-wat-2',
    name: '평촌중앙공원 분수광장 음수대',
    category: 'water',
    categoryName: '음수대',
    lat: 37.3920,
    lng: 126.9570,
    district: '동안구',
    address: '경기 안양시 동안구 관양동 1601 (중앙공원 중앙 분수대 옆)',
    description: '평촌중앙공원 메인 트랙 옆 음수대. 실시간 수질 측정 및 냉음수 제공.',
    openHours: '24시간 상시 개방',
    facilityType: '공원 음수대',
    managementAgency: '동안구청 공원관리과',
    availableItems: ['냉음수 직수', '다회용 텀블러 급수구'],
  },
  {
    id: 'fac-wat-3',
    name: '안양천 삼덕교 하부 음수대',
    category: 'water',
    categoryName: '음수대',
    lat: 37.4014,
    lng: 126.9208,
    district: '만안구',
    address: '경기 안양시 만안구 안양동 삼덕교 하부 둔치',
    description: '안양천 만안구 구간 주요 라이더 급수 지점.',
    openHours: '상시 이용 가능',
    facilityType: '수변 음수대',
    managementAgency: '안양시 수도시설과',
    availableItems: ['물통 직수 레버', '수질검사 완료'],
  },
  {
    id: 'fac-wat-4',
    name: '학운공원 롤러장 옆 음수대',
    category: 'water',
    categoryName: '음수대',
    lat: 37.3978,
    lng: 126.9530,
    district: '동안구',
    address: '경기 안양시 동안구 달안동 학운공원',
    description: '학의천변 학운공원 체육공간 내 음수대.',
    openHours: '상시 이용 가능',
    facilityType: '공원 음수대',
    managementAgency: '동안구청 공원관리과',
    availableItems: ['직수 레버', '상시 수질관리'],
  },

  // ==========================================
  // 6. 라이더 쉼터 / 카페 (cafe)
  // ==========================================
  {
    id: 'fac-cafe-1',
    name: '쌍개울 수변 라이더 카페 & 편의점',
    category: 'cafe',
    categoryName: '라이더 카페',
    lat: 37.3950,
    lng: 126.9572,
    district: '동안구',
    address: '경기 안양시 동안구 비산동 1115 (비산교 남단)',
    description: '안양천 라이더들이 가장 많이 찾는 성지. 자전거 전용 거치대 30대 구비, 시원한 음료, 에너지바, 타이어 튜브 판매.',
    openHours: '매일 07:00 ~ 23:00',
    facilityType: '라이더 카페/편의점',
    availableItems: ['자전거 전용 랙 30대', '타이어 튜브/CO2 판매', '야외 테라스 테이블', '스마트폰 급속충전'],
  },
  {
    id: 'fac-cafe-2',
    name: '안양예술공원 수변 베이커리 쉼터',
    category: 'cafe',
    categoryName: '수변 쉼터/카페',
    lat: 37.4252,
    lng: 126.9285,
    district: '만안구',
    address: '경기 안양시 만안구 예술공원로 152',
    description: '삼성천 맑은 계곡 옆 베이커리 카페. 자전거 전용 거치대 및 야외 휴식 테라스.',
    openHours: '매일 09:00 ~ 22:00',
    facilityType: '수변 카페',
    availableItems: ['자전거 거치대 20대', '무료 타이어 펌프 대여', '계곡 뷰 테라스'],
  },
  {
    id: 'fac-cafe-3',
    name: '병목안 수변 정자 쉼터',
    category: 'cafe',
    categoryName: '수변 쉼터',
    lat: 37.3830,
    lng: 126.9055,
    district: '만안구',
    address: '경기 안양시 만안구 안양9동 산81 병목안시민공원 입구',
    description: '수리산 자락 시원한 그늘막 정자 쉼터. 라이더들을 위한 평상과 벤치 완비.',
    openHours: '24시간 상시 개방',
    facilityType: '공공 쉼터',
    availableItems: ['그늘막 정자', '야외 벤치', '자전거 거치대'],
  },
];

export const ANYANG_BICYCLE_FACILITIES = ANYANG_FACILITIES;
